In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('Amazonbookreviews.csv')

In [7]:
data

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
0,A2SUAM1J3GNN3B,23456.0,SNEHA,2,I bought this for my husband who plays the pia...,4.0,SUBWAY SURF,NaN,NaN
1,A2SUAN1J3GNN0C,879877.0,KARTHII,3,good book to read,3.0,PILOT,NaN,NaN
2,A2SUAN1J3GNN7B,23456.0,SHASHANK,3,high cost,2.5,DRIVE IN HEAVEN,NaN,NaN
3,A5SUAN1J3GNN9B,67578.0,NITIN,3,good useof book,2.2,SPORTS HEAVEN,NaN,NaN
4,A1SUAM1J3GNN3B,123.0,PRANOTI,3,I m happy with the book,3.0,HEAVEN OF PEARLS,NaN,NaN
5,BA2345WERSDFRER,236789.0,SHALINI,3,im not happy with the delay of product,3.0,GODS GIFT,NaN,NaN
6,CADERVG3450EREW,NaN,SNEHAL,3,delay in book,3.0,GODESS LIFE,NaN,NaN
7,ASDF345671QWERT,224442.0,SHIKHA,3,Wonderful book,3.0,LIFE OF PIE,NaN,NaN
8,MNHJ879WERFGH,98767.0,AKSHAY,2,The music is at times hard to read because we ...,3.0,INDIA A MASSIVE POWER,NaN,NaN
9,1234ZSDFREQWEG,78761.0,SATISH,2,many errors,5.0,DATA IS DATA,NaN,NaN
10,9345GHIKLFLLED,321456.0,RAJU,2,no mini,4.0,INDIA A MASSIVE POWER,NaN,NaN
11,NaN,876231.0,ROHIT,2,high vat,4.0,FRIENDS HELP,NaN,NaN
12,HGKIUYE345SFDG,987.0,MOHIT,2,the dealer is charged more money,4.0,MOTIVATIONAL,NaN,NaN
13,NIKRT2398701222,234.0,NILESH,2,helpful,3.0,DARK KNIGHT,NaN,NaN
14,MAHI2348900122,124.0,KAILASH,2,staff is good,3.0,HELL OF HELL,NaN,NaN
15,LIHJKD87634O21,156.0,SONAM,2,good buy for money,3.0,DEAA,NaN,NaN
16,SISISWER4657893,876.0,RAJESH,2,money is dis,3.0,DEAR TO ALL,NaN,NaN
17,MIKI23412341QW,123.0,SALMAN,2,stare the raeder,2.0,MOTHER,NaN,NaN
18,AAAJI37DFG378I,987.0,PANKAJ,2,reader is giood,2.0,WINE OF WINE,NaN,NaN
19,FAJI234GAJI987,22456.0,DIPTI,2,faskjas,2.0,INDIA IS MY COUNTRY,NaN,NaN
20,VABI9876ERTT1,9876.0,MANISH,2,fdghi,2.0,ONE FOR ALLL,NaN,NaN
21,NIKI12NIKI1231,3451.0,SHREYA,2,dvdasaewb,4.0,DATA IS DATA,NaN,NaN
22,MIKISDF1232XAD,879.0,AISHWARYA,2,NA,4.0,INDIA A MASSIVE POWER,NaN,NaN
23,GHAU8768QWER,321.0,SUMEET,2,NA,4.0,FRIENDS HELP,NaN,NaN
24,NIKI12NIKI1231,2.0,PRAJWAL,3,NA,4.0,MOTIVATIONAL,NaN,NaN
25,MIKISDF1232XAD,1.0,JACOB,3,0.888888888,4.0,DARK KNIGHT,NaN,NaN
26,GHAU8768QWER,23.0,MARYLS,3,9.666666667,4.0,HELL OF HELL,NaN,NaN
27,BA2345WERSDFRER,11.0,CHRIS,3,helpful,4.0,DEAA,NaN,NaN
28,CADERVG3450EREW,11.0,MORRIS,3,staff is good,4.0,DEAR TO ALL,NaN,NaN
29,ASDF345671QWERT,23.0,HARRY,3,good buy for money,4.0,MOTHER,NaN,NaN
30,MNHJ879WERFGH,21221.0,JOHN,3,money is dis,4.0,WINE OF WINE,NaN,NaN
31,1234ZSDFREQWEG,21.0,VARSHA,3,stare the raeder,4.0,INDIA IS MY COUNTRY,NaN,NaN
32,9345GHIKLFLLED,12212.0,SHRADDHA,3,reader is giood,3.0,ONE FOR ALLL,NaN,NaN
33,NaN,2121.0,SAIF,3,faskjas,3.0,helpful,NaN,NaN
34,HGKIUYE345SFDG,21212.0,KRISSH,3,fdghi,3.0,staff is good,NaN,NaN
35,NIKRT2398701222,21221.0,NEIL,3,8.78E+21,3.0,good buy for money,NaN,NaN
36,MAHI2348900122,22245.0,KANGANA,3,67667,2.0,money is dis,NaN,NaN
37,LIHJKD87634O21,678.0,KHANN,3,3434567,2.0,stare the raeder,NaN,NaN
38,SISISWER4657893,111.0,RIYAA,3,098O,2.0,reader is giood,NaN,NaN
39,8786112GHAUI,223.0,NaN,3,GOOD LUCK,2.0,faskjas,NaN,NaN
40,67FDASAA123,2312.0,NANAJJI,3,BYE MY LOVE,4.0,HELL OF HELL,NaN,NaN
41,ASWER1234,1222.0,PREETI,2,LOVE U,4.0,DEAA,NaN,NaN
42,QWCVFED123,11111.0,DHONI,2,HELLO DEAR,4.0,DEAR TO ALL,NaN,NaN
43,123LKIUHNFG,9800.0,MAHI,2,DAER PLEASE READ BOOK,4.0,MOTHER,NaN,NaN
44,987DFHGJI657,NaN,DDE,2,BOOK,4.0,WINE OF WINE,NaN,NaN

In [9]:
data.head()

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
0,A2SUAM1J3GNN3B,23456.0,SNEHA,2,I bought this for my husband who plays the pia...,4.0,SUBWAY SURF,NaN,NaN
1,A2SUAN1J3GNN0C,879877.0,KARTHII,3,good book to read,3.0,PILOT,NaN,NaN
2,A2SUAN1J3GNN7B,23456.0,SHASHANK,3,high cost,2.5,DRIVE IN HEAVEN,NaN,NaN
3,A5SUAN1J3GNN9B,67578.0,NITIN,3,good useof book,2.2,SPORTS HEAVEN,NaN,NaN
4,A1SUAM1J3GNN3B,123.0,PRANOTI,3,I m happy with the book,3.0,HEAVEN OF PEARLS,NaN,NaN

In [11]:
data.tail()

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
40,67FDASAA123,2312.0,NANAJJI,3,BYE MY LOVE,4.0,HELL OF HELL,NaN,NaN
41,ASWER1234,1222.0,PREETI,2,LOVE U,4.0,DEAA,NaN,NaN
42,QWCVFED123,11111.0,DHONI,2,HELLO DEAR,4.0,DEAR TO ALL,NaN,NaN
43,123LKIUHNFG,9800.0,MAHI,2,DAER PLEASE READ BOOK,4.0,MOTHER,NaN,NaN
44,987DFHGJI657,NaN,DDE,2,BOOK,4.0,WINE OF WINE,NaN,NaN

In [13]:
data.describe()

                asin    helpful  overallRating  UnixreviewTime  reviewTime
count      43.000000  45.000000      45.000000             0.0         0.0
mean    69702.023256   2.533333       3.282222             NaN         NaN
std    193175.237815   0.504525       0.816113             NaN         NaN
min         1.000000   2.000000       2.000000             NaN         NaN
25%       140.000000   2.000000       3.000000             NaN         NaN
50%      2121.000000   3.000000       3.000000             NaN         NaN
75%     22350.500000   3.000000       4.000000             NaN         NaN
max    879877.000000   3.000000       5.000000             NaN         NaN

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      43 non-null     object
 1   asin            43 non-null     float64
 2   reviewername    44 non-null     object
 3   helpful         45 non-null     int64
 4   reviewerText    45 non-null     object
 5   overallRating   45 non-null     float64
 6   Summary         45 non-null     object
 7   UnixreviewTime  0 non-null      float64
 8   reviewTime      0 non-null      float64
dtypes: float64(4), int64(1), object(4)
memory usage: 3.3+ KB

In [17]:
data.shape

(45, 9)

In [19]:
data.isnull()

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
0,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,False,True,True
6,False,True,False,False,False,False,False,True,True
7,False,False,False,False,False,False,False,True,True
8,False,False,False,False,False,False,False,True,True
9,False,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,False,True,True
11,True,False,False,False,False,False,False,True,True
12,False,False,False,False,False,False,False,True,True
13,False,False,False,False,False,False,False,True,True
14,False,False,False,False,False,False,False,True,True
15,False,False,False,False,False,False,False,True,True
16,False,False,False,False,False,False,False,True,True
17,False,False,False,False,False,False,False,True,True
18,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,False,True,True
22,False,False,False,False,False,False,False,True,True
23,False,False,False,False,False,False,False,True,True
24,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,False,True,True
27,False,False,False,False,False,False,False,True,True
28,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,True,True
30,False,False,False,False,False,False,False,True,True
31,False,False,False,False,False,False,False,True,True
32,False,False,False,False,False,False,False,True,True
33,True,False,False,False,False,False,False,True,True
34,False,False,False,False,False,False,False,True,True
35,False,False,False,False,False,False,False,True,True
36,False,False,False,False,False,False,False,True,True
37,False,False,False,False,False,False,False,True,True
38,False,False,False,False,False,False,False,True,True
39,False,False,True,False,False,False,False,True,True
40,False,False,False,False,False,False,False,True,True
41,False,False,False,False,False,False,False,True,True
42,False,False,False,False,False,False,False,True,True
43,False,False,False,False,False,False,False,True,True
44,False,True,False,False,False,False,False,True,True

In [21]:
data.isnull().sum()

reviewerID         2
asin               2
reviewername       1
helpful            0
reviewerText       0
overallRating      0
Summary            0
UnixreviewTime    45
reviewTime        45
dtype: int64

In [49]:
#creating subsets row wise

df1 = data[['reviewerID','reviewername','reviewerText','overallRating']].loc[0:15]
df1

,reviewerID,reviewername,reviewerText,overallRating
0,A2SUAM1J3GNN3B,SNEHA,I bought this for my husband who plays the pia...,4.0
1,A2SUAN1J3GNN0C,KARTHII,good book to read,3.0
2,A2SUAN1J3GNN7B,SHASHANK,high cost,2.5
3,A5SUAN1J3GNN9B,NITIN,good useof book,2.2
4,A1SUAM1J3GNN3B,PRANOTI,I m happy with the book,3.0
5,BA2345WERSDFRER,SHALINI,im not happy with the delay of product,3.0
6,CADERVG3450EREW,SNEHAL,delay in book,3.0
7,ASDF345671QWERT,SHIKHA,Wonderful book,3.0
8,MNHJ879WERFGH,AKSHAY,The music is at times hard to read because we ...,3.0
9,1234ZSDFREQWEG,SATISH,many errors,5.0
10,9345GHIKLFLLED,RAJU,no mini,4.0
11,NaN,ROHIT,high vat,4.0
12,HGKIUYE345SFDG,MOHIT,the dealer is charged more money,4.0
13,NIKRT2398701222,NILESH,helpful,3.0
14,MAHI2348900122,KAILASH,staff is good,3.0
15,LIHJKD87634O21,SONAM,good buy for money,3.0

In [27]:
df2 = data[['reviewerID','reviewername','reviewerText','overallRating']].loc[16:30]
df2

         reviewerID reviewername        reviewerText  overallRating
16  SISISWER4657893       RAJESH       money is dis             3.0
17   MIKI23412341QW       SALMAN    stare the raeder            2.0
18   AAAJI37DFG378I       PANKAJ     reader is giood            2.0
19   FAJI234GAJI987        DIPTI             faskjas            2.0
20    VABI9876ERTT1       MANISH               fdghi            2.0
21   NIKI12NIKI1231       SHREYA           dvdasaewb            4.0
22   MIKISDF1232XAD    AISHWARYA                 NA             4.0
23     GHAU8768QWER       SUMEET                 NA             4.0
24   NIKI12NIKI1231      PRAJWAL                 NA             4.0
25   MIKISDF1232XAD        JACOB         0.888888888            4.0
26     GHAU8768QWER       MARYLS         9.666666667            4.0
27  BA2345WERSDFRER        CHRIS             helpful            4.0
28  CADERVG3450EREW       MORRIS       staff is good            4.0
29  ASDF345671QWERT        HARRY  good buy for money            4.0
30    MNHJ879WERFGH         JOHN       money is dis             4.0

In [29]:
df3 = data[['reviewerID','reviewername','reviewerText','overallRating']].loc[31:44]
df3

         reviewerID reviewername           reviewerText  overallRating
31   1234ZSDFREQWEG       VARSHA       stare the raeder            4.0
32   9345GHIKLFLLED     SHRADDHA        reader is giood            3.0
33              NaN         SAIF                faskjas            3.0
34   HGKIUYE345SFDG       KRISSH                  fdghi            3.0
35  NIKRT2398701222         NEIL               8.78E+21            3.0
36   MAHI2348900122      KANGANA                  67667            2.0
37   LIHJKD87634O21        KHANN                3434567            2.0
38  SISISWER4657893        RIYAA                   098O            2.0
39     8786112GHAUI          NaN              GOOD LUCK            2.0
40      67FDASAA123      NANAJJI            BYE MY LOVE            4.0
41        ASWER1234       PREETI                LOVE U             4.0
42       QWCVFED123        DHONI             HELLO DEAR            4.0
43      123LKIUHNFG         MAHI  DAER PLEASE READ BOOK            4.0
44     987DFHGJI657          DDE                   BOOK            4.0

In [55]:
#column wise
amazon_subset1 = data[['reviewerID', 'overallRating', 'reviewerText']]
amazon_subset1

,reviewerID,overallRating,reviewerText
0,A2SUAM1J3GNN3B,4.0,I bought this for my husband who plays the pia...
1,A2SUAN1J3GNN0C,3.0,good book to read
2,A2SUAN1J3GNN7B,2.5,high cost
3,A5SUAN1J3GNN9B,2.2,good useof book
4,A1SUAM1J3GNN3B,3.0,I m happy with the book
5,BA2345WERSDFRER,3.0,im not happy with the delay of product
6,CADERVG3450EREW,3.0,delay in book
7,ASDF345671QWERT,3.0,Wonderful book
8,MNHJ879WERFGH,3.0,The music is at times hard to read because we ...
9,1234ZSDFREQWEG,5.0,many errors
10,9345GHIKLFLLED,4.0,no mini
11,NaN,4.0,high vat
12,HGKIUYE345SFDG,4.0,the dealer is charged more money
13,NIKRT2398701222,3.0,helpful
14,MAHI2348900122,3.0,staff is good
15,LIHJKD87634O21,3.0,good buy for money
16,SISISWER4657893,3.0,money is dis
17,MIKI23412341QW,2.0,stare the raeder
18,AAAJI37DFG378I,2.0,reader is giood
19,FAJI234GAJI987,2.0,faskjas
20,VABI9876ERTT1,2.0,fdghi
21,NIKI12NIKI1231,4.0,dvdasaewb
22,MIKISDF1232XAD,4.0,NA
23,GHAU8768QWER,4.0,NA
24,NIKI12NIKI1231,4.0,NA
25,MIKISDF1232XAD,4.0,0.888888888
26,GHAU8768QWER,4.0,9.666666667
27,BA2345WERSDFRER,4.0,helpful
28,CADERVG3450EREW,4.0,staff is good
29,ASDF345671QWERT,4.0,good buy for money
30,MNHJ879WERFGH,4.0,money is dis
31,1234ZSDFREQWEG,4.0,stare the raeder
32,9345GHIKLFLLED,3.0,reader is giood
33,NaN,3.0,faskjas
34,HGKIUYE345SFDG,3.0,fdghi
35,NIKRT2398701222,3.0,8.78E+21
36,MAHI2348900122,2.0,67667
37,LIHJKD87634O21,2.0,3434567
38,SISISWER4657893,2.0,098O
39,8786112GHAUI,2.0,GOOD LUCK
40,67FDASAA123,4.0,BYE MY LOVE
41,ASWER1234,4.0,LOVE U
42,QWCVFED123,4.0,HELLO DEAR
43,123LKIUHNFG,4.0,DAER PLEASE READ BOOK
44,987DFHGJI657,4.0,BOOK

In [59]:
amazon_subset2 = data[['helpful','Summary','reviewername']]
amazon_subset2

    helpful                Summary reviewername
0         2            SUBWAY SURF        SNEHA
1         3                 PILOT       KARTHII
2         3        DRIVE IN HEAVEN     SHASHANK
3         3          SPORTS HEAVEN        NITIN
4         3       HEAVEN OF PEARLS      PRANOTI
5         3              GODS GIFT      SHALINI
6         3            GODESS LIFE       SNEHAL
7         3            LIFE OF PIE       SHIKHA
8         2  INDIA A MASSIVE POWER       AKSHAY
9         2           DATA IS DATA       SATISH
10        2  INDIA A MASSIVE POWER         RAJU
11        2           FRIENDS HELP        ROHIT
12        2           MOTIVATIONAL        MOHIT
13        2            DARK KNIGHT       NILESH
14        2           HELL OF HELL      KAILASH
15        2                   DEAA        SONAM
16        2            DEAR TO ALL       RAJESH
17        2                MOTHER        SALMAN
18        2           WINE OF WINE       PANKAJ
19        2   INDIA IS MY COUNTRY         DIPTI
20        2           ONE FOR ALLL       MANISH
21        2           DATA IS DATA       SHREYA
22        2  INDIA A MASSIVE POWER    AISHWARYA
23        2           FRIENDS HELP       SUMEET
24        3           MOTIVATIONAL      PRAJWAL
25        3            DARK KNIGHT        JACOB
26        3           HELL OF HELL       MARYLS
27        3                   DEAA        CHRIS
28        3            DEAR TO ALL       MORRIS
29        3                MOTHER         HARRY
30        3           WINE OF WINE         JOHN
31        3   INDIA IS MY COUNTRY        VARSHA
32        3           ONE FOR ALLL     SHRADDHA
33        3                helpful         SAIF
34        3          staff is good       KRISSH
35        3     good buy for money         NEIL
36        3          money is dis       KANGANA
37        3       stare the raeder        KHANN
38        3        reader is giood        RIYAA
39        3                faskjas          NaN
40        3           HELL OF HELL      NANAJJI
41        2                   DEAA       PREETI
42        2            DEAR TO ALL        DHONI
43        2                MOTHER          MAHI
44        2           WINE OF WINE          DDE

In [61]:
#merging of data row wise
merge = pd.concat([df1,df2,df3])
merge

,reviewerID,reviewername,reviewerText,overallRating
0,A2SUAM1J3GNN3B,SNEHA,I bought this for my husband who plays the pia...,4.0
1,A2SUAN1J3GNN0C,KARTHII,good book to read,3.0
2,A2SUAN1J3GNN7B,SHASHANK,high cost,2.5
3,A5SUAN1J3GNN9B,NITIN,good useof book,2.2
4,A1SUAM1J3GNN3B,PRANOTI,I m happy with the book,3.0
5,BA2345WERSDFRER,SHALINI,im not happy with the delay of product,3.0
6,CADERVG3450EREW,SNEHAL,delay in book,3.0
7,ASDF345671QWERT,SHIKHA,Wonderful book,3.0
8,MNHJ879WERFGH,AKSHAY,The music is at times hard to read because we ...,3.0
9,1234ZSDFREQWEG,SATISH,many errors,5.0
10,9345GHIKLFLLED,RAJU,no mini,4.0
11,NaN,ROHIT,high vat,4.0
12,HGKIUYE345SFDG,MOHIT,the dealer is charged more money,4.0
13,NIKRT2398701222,NILESH,helpful,3.0
14,MAHI2348900122,KAILASH,staff is good,3.0
15,LIHJKD87634O21,SONAM,good buy for money,3.0
16,SISISWER4657893,RAJESH,money is dis,3.0
17,MIKI23412341QW,SALMAN,stare the raeder,2.0
18,AAAJI37DFG378I,PANKAJ,reader is giood,2.0
19,FAJI234GAJI987,DIPTI,faskjas,2.0
20,VABI9876ERTT1,MANISH,fdghi,2.0
21,NIKI12NIKI1231,SHREYA,dvdasaewb,4.0
22,MIKISDF1232XAD,AISHWARYA,NA,4.0
23,GHAU8768QWER,SUMEET,NA,4.0
24,NIKI12NIKI1231,PRAJWAL,NA,4.0
25,MIKISDF1232XAD,JACOB,0.888888888,4.0
26,GHAU8768QWER,MARYLS,9.666666667,4.0
27,BA2345WERSDFRER,CHRIS,helpful,4.0
28,CADERVG3450EREW,MORRIS,staff is good,4.0
29,ASDF345671QWERT,HARRY,good buy for money,4.0
30,MNHJ879WERFGH,JOHN,money is dis,4.0
31,1234ZSDFREQWEG,VARSHA,stare the raeder,4.0
32,9345GHIKLFLLED,SHRADDHA,reader is giood,3.0
33,NaN,SAIF,faskjas,3.0
34,HGKIUYE345SFDG,KRISSH,fdghi,3.0
35,NIKRT2398701222,NEIL,8.78E+21,3.0
36,MAHI2348900122,KANGANA,67667,2.0
37,LIHJKD87634O21,KHANN,3434567,2.0
38,SISISWER4657893,RIYAA,098O,2.0
39,8786112GHAUI,NaN,GOOD LUCK,2.0
40,67FDASAA123,NANAJJI,BYE MY LOVE,4.0
41,ASWER1234,PREETI,LOVE U,4.0
42,QWCVFED123,DHONI,HELLO DEAR,4.0
43,123LKIUHNFG,MAHI,DAER PLEASE READ BOOK,4.0
44,987DFHGJI657,DDE,BOOK,4.0

In [63]:
#merge column wise
merge = pd.concat([amazon_subset1,amazon_subset2])
merge

,reviewerID,overallRating,reviewerText,helpful,Summary,reviewername
0,A2SUAM1J3GNN3B,4.0,I bought this for my husband who plays the pia...,NaN,NaN,NaN
1,A2SUAN1J3GNN0C,3.0,good book to read,NaN,NaN,NaN
2,A2SUAN1J3GNN7B,2.5,high cost,NaN,NaN,NaN
3,A5SUAN1J3GNN9B,2.2,good useof book,NaN,NaN,NaN
4,A1SUAM1J3GNN3B,3.0,I m happy with the book,NaN,NaN,NaN
...,...,...,...,...,...,...
40,NaN,NaN,NaN,3.0,HELL OF HELL,NANAJJI
41,NaN,NaN,NaN,2.0,DEAA,PREETI
42,NaN,NaN,NaN,2.0,DEAR TO ALL,DHONI
43,NaN,NaN,NaN,2.0,MOTHER,MAHI
44,NaN,NaN,NaN,2.0,WINE OF WINE,DDE

In [35]:
sort = data.sort_values('overallRating', ascending = False)
sort

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
9,1234ZSDFREQWEG,78761.0,SATISH,2,many errors,5.0,DATA IS DATA,NaN,NaN
0,A2SUAM1J3GNN3B,23456.0,SNEHA,2,I bought this for my husband who plays the pia...,4.0,SUBWAY SURF,NaN,NaN
21,NIKI12NIKI1231,3451.0,SHREYA,2,dvdasaewb,4.0,DATA IS DATA,NaN,NaN
43,123LKIUHNFG,9800.0,MAHI,2,DAER PLEASE READ BOOK,4.0,MOTHER,NaN,NaN
42,QWCVFED123,11111.0,DHONI,2,HELLO DEAR,4.0,DEAR TO ALL,NaN,NaN
41,ASWER1234,1222.0,PREETI,2,LOVE U,4.0,DEAA,NaN,NaN
40,67FDASAA123,2312.0,NANAJJI,3,BYE MY LOVE,4.0,HELL OF HELL,NaN,NaN
31,1234ZSDFREQWEG,21.0,VARSHA,3,stare the raeder,4.0,INDIA IS MY COUNTRY,NaN,NaN
30,MNHJ879WERFGH,21221.0,JOHN,3,money is dis,4.0,WINE OF WINE,NaN,NaN
29,ASDF345671QWERT,23.0,HARRY,3,good buy for money,4.0,MOTHER,NaN,NaN
28,CADERVG3450EREW,11.0,MORRIS,3,staff is good,4.0,DEAR TO ALL,NaN,NaN
27,BA2345WERSDFRER,11.0,CHRIS,3,helpful,4.0,DEAA,NaN,NaN
26,GHAU8768QWER,23.0,MARYLS,3,9.666666667,4.0,HELL OF HELL,NaN,NaN
25,MIKISDF1232XAD,1.0,JACOB,3,0.888888888,4.0,DARK KNIGHT,NaN,NaN
24,NIKI12NIKI1231,2.0,PRAJWAL,3,NA,4.0,MOTIVATIONAL,NaN,NaN
23,GHAU8768QWER,321.0,SUMEET,2,NA,4.0,FRIENDS HELP,NaN,NaN
22,MIKISDF1232XAD,879.0,AISHWARYA,2,NA,4.0,INDIA A MASSIVE POWER,NaN,NaN
44,987DFHGJI657,NaN,DDE,2,BOOK,4.0,WINE OF WINE,NaN,NaN
12,HGKIUYE345SFDG,987.0,MOHIT,2,the dealer is charged more money,4.0,MOTIVATIONAL,NaN,NaN
11,NaN,876231.0,ROHIT,2,high vat,4.0,FRIENDS HELP,NaN,NaN
10,9345GHIKLFLLED,321456.0,RAJU,2,no mini,4.0,INDIA A MASSIVE POWER,NaN,NaN
8,MNHJ879WERFGH,98767.0,AKSHAY,2,The music is at times hard to read because we ...,3.0,INDIA A MASSIVE POWER,NaN,NaN
4,A1SUAM1J3GNN3B,123.0,PRANOTI,3,I m happy with the book,3.0,HEAVEN OF PEARLS,NaN,NaN
5,BA2345WERSDFRER,236789.0,SHALINI,3,im not happy with the delay of product,3.0,GODS GIFT,NaN,NaN
35,NIKRT2398701222,21221.0,NEIL,3,8.78E+21,3.0,good buy for money,NaN,NaN
34,HGKIUYE345SFDG,21212.0,KRISSH,3,fdghi,3.0,staff is good,NaN,NaN
33,NaN,2121.0,SAIF,3,faskjas,3.0,helpful,NaN,NaN
32,9345GHIKLFLLED,12212.0,SHRADDHA,3,reader is giood,3.0,ONE FOR ALLL,NaN,NaN
7,ASDF345671QWERT,224442.0,SHIKHA,3,Wonderful book,3.0,LIFE OF PIE,NaN,NaN
6,CADERVG3450EREW,NaN,SNEHAL,3,delay in book,3.0,GODESS LIFE,NaN,NaN
13,NIKRT2398701222,234.0,NILESH,2,helpful,3.0,DARK KNIGHT,NaN,NaN
14,MAHI2348900122,124.0,KAILASH,2,staff is good,3.0,HELL OF HELL,NaN,NaN
15,LIHJKD87634O21,156.0,SONAM,2,good buy for money,3.0,DEAA,NaN,NaN
1,A2SUAN1J3GNN0C,879877.0,KARTHII,3,good book to read,3.0,PILOT,NaN,NaN
16,SISISWER4657893,876.0,RAJESH,2,money is dis,3.0,DEAR TO ALL,NaN,NaN
2,A2SUAN1J3GNN7B,23456.0,SHASHANK,3,high cost,2.5,DRIVE IN HEAVEN,NaN,NaN
3,A5SUAN1J3GNN9B,67578.0,NITIN,3,good useof book,2.2,SPORTS HEAVEN,NaN,NaN
18,AAAJI37DFG378I,987.0,PANKAJ,2,reader is giood,2.0,WINE OF WINE,NaN,NaN
36,MAHI2348900122,22245.0,KANGANA,3,67667,2.0,money is dis,NaN,NaN
37,LIHJKD87634O21,678.0,KHANN,3,3434567,2.0,stare the raeder,NaN,NaN
38,SISISWER4657893,111.0,RIYAA,3,098O,2.0,reader is giood,NaN,NaN
39,8786112GHAUI,223.0,NaN,3,GOOD LUCK,2.0,faskjas,NaN,NaN
20,VABI9876ERTT1,9876.0,MANISH,2,fdghi,2.0,ONE FOR ALLL,NaN,NaN
19,FAJI234GAJI987,22456.0,DIPTI,2,faskjas,2.0,INDIA IS MY COUNTRY,NaN,NaN
17,MIKI23412341QW,123.0,SALMAN,2,stare the raeder,2.0,MOTHER,NaN,NaN

In [39]:
df1.transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
reviewerID,A2SUAM1J3GNN3B,A2SUAN1J3GNN0C,A2SUAN1J3GNN7B,A5SUAN1J3GNN9B,A1SUAM1J3GNN3B,BA2345WERSDFRER,CADERVG3450EREW,ASDF345671QWERT,MNHJ879WERFGH,1234ZSDFREQWEG,9345GHIKLFLLED,NaN,HGKIUYE345SFDG,NIKRT2398701222,MAHI2348900122,LIHJKD87634O21
reviewername,SNEHA,KARTHII,SHASHANK,NITIN,PRANOTI,SHALINI,SNEHAL,SHIKHA,AKSHAY,SATISH,RAJU,ROHIT,MOHIT,NILESH,KAILASH,SONAM
reviewerText,I bought this for my husband who plays the pia...,good book to read,high cost,good useof book,I m happy with the book,im not happy with the delay of product,delay in book,Wonderful book,The music is at times hard to read because we ...,many errors,no mini,high vat,the dealer is charged more money,helpful,staff is good,good buy for money
overallRating,4.0,3.0,2.5,2.2,3.0,3.0,3.0,3.0,3.0,5.0,4.0,4.0,4.0,3.0,3.0,3.0

In [43]:
shaping=data.shape
shaping

(45, 9)

In [47]:
pivot_table = pd.pivot_table(data,index = ['reviewername','reviewerText'], values = 'overallRating')
print(pivot_table)

                                                                 overallRating
reviewername reviewerText
AISHWARYA    NA                                                            4.0
AKSHAY       The music is at times hard to read because we t...            3.0
CHRIS        helpful                                                       4.0
DDE          BOOK                                                          4.0
DHONI        HELLO DEAR                                                    4.0
DIPTI        faskjas                                                       2.0
HARRY        good buy for money                                            4.0
JACOB        0.888888888                                                   4.0
JOHN         money is dis                                                  4.0
KAILASH      staff is good                                                 3.0
KANGANA      67667                                                         2.0
KARTHII      good book to read                                             3.0
KHANN        3434567                                                       2.0
KRISSH       fdghi                                                         3.0
MAHI         DAER PLEASE READ BOOK                                         4.0
MANISH       fdghi                                                         2.0
MARYLS       9.666666667                                                   4.0
MOHIT        the dealer is charged more money                              4.0
MORRIS       staff is good                                                 4.0
NANAJJI      BYE MY LOVE                                                   4.0
NEIL         8.78E+21                                                      3.0
NILESH       helpful                                                       3.0
NITIN        good useof book                                               2.2
PANKAJ       reader is giood                                               2.0
PRAJWAL      NA                                                            4.0
PRANOTI      I m happy with the book                                       3.0
PREETI       LOVE U                                                        4.0
RAJESH       money is dis                                                  3.0
RAJU         no mini                                                       4.0
RIYAA        098O                                                          2.0
ROHIT        high vat                                                      4.0
SAIF         faskjas                                                       3.0
SALMAN       stare the raeder                                              2.0
SATISH       many errors                                                   5.0
SHALINI      im not happy with the delay of product                        3.0
SHASHANK     high cost                                                     2.5
SHIKHA       Wonderful book                                                3.0
SHRADDHA     reader is giood                                               3.0
SHREYA       dvdasaewb                                                     4.0
SNEHA        I bought this for my husband who plays the pian...            4.0
SNEHAL       delay in book                                                 3.0
SONAM        good buy for money                                            3.0
SUMEET       NA                                                            4.0
VARSHA       stare the raeder                                              4.0